title:             旅と日常と
email:             your-email@example.com
description:       旅の記録や書きたいことを適当に
author:            mencha
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://menchan.github.io"

# Social Profiles
twitter_username:  mencha_pimi
github_username:   
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
