title:             test blog
email:             your-email@example.com
description:       テストブログです
author:            mencha
baseurl:           ""
url:               "http://menchan.github.io"

# Social Profiles
twitter_username:  mencha_pimi
github_username:   
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
